name: auth_repository
description: "Authentication repository for the m3t attendee app."
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  m3t_api:
    path: ../m3t_api
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
